# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      VERSION: "1.2"
    
    steps:
      - checkout
      - run: gem install package_cloud
      - run: sudo apt-get install openjdk-8-jdk
      - run: sudo apt-get install maven
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn integration-test
      - run: mvn package
      - run: package_cloud push AppOptics/kafka-appoptics-reporter/java target/kafka-appoptics-reporter-$VERSION.jar --coordinates=com.appoptics.integrations.kafka:kafka-appoptics-reporter:$VERSION
